- CHANGELOG.md
- README.md
- package.json
This commit starts work needed to rename the repo and
the binary it produces from `nebula-cli` to `relay`.
No code updates, just metadata.
> Updates to rename repo - metadata/text only!

- pkg/client/workflow.go
- pkg/cmd/workflow.go
Adds a `-f` option to `relay workflow download` for specifying
output file, to match the other `relay workflow *` commands
Adds a shortcut `-p` for `--parameter` on `relay workflow run`
Closes #33
> Improvements to workflow subcommand

- docs/generate.go
- docs/relay.md
- go.sum
- pkg/cmd/doc.go
- pkg/cmd/main.go
This adds a `relay doc generate` command that can build
man and markdown format doc trees.
The output format is not ideal; I'd like to have a "real"
manpage that has all the subcommands documented in one page,
and same with the markdown. But it's better than nothing.
The output is meant to be checked into the docs repo or viewed
locally.
> Updates for PN-706 - add documentation for the CLI

- README.md
- build/package/archlinux/PKGBUILD
- build/package/brew/relay-cli-update-brew.yaml
- pkg/client/request.go
- pkg/client/revision.go
- pkg/config/config.go
There were a few stray references to nebula in the docs
and internally in the code. This updates the API endpoints
and custom content-type, packaging scripts, and README.
> Batch of renames for nebula->relay production push

- README.md
Use a direct link to the #relay channel in the Puppet Community Slack: https://puppetcommunity.slack.com/archives/CMKBMAW2K
Related: https://github.com/puppetlabs/relay-ui/pull/164
> Update Slack link in README.md

- docs/relay.md
- pkg/cluster/cluster.go
- pkg/cluster/k3d.go
- pkg/cmd/cluster.go
Allows the number of worker nodes to be configured, rather than the previously hardcoded value of 2.
Default number of worker nodes remains 2.
Setting this value to 0 will apply the appropriate labels to the server node to support a fully functional single node.
Configuration option naming could stand to be more clear...
> Add configuration for worker count

- pkg/model/revision.go
The parameter type (for the default value) is currently inconsistent with the rest of the system. This currently prevents downloading, adding, or replacing a workflow if anything other than a string is used for parameters (bool, int, etc.).
> Fix parameter type

- pkg/dev/dev.go
The expected namespace may not exist during the cluster deletion for a variety of valid reasons.
> Do not prematurely abort cluster deletion

- pkg/cmd/workflow.go
- pkg/dialog/dialog.go
Add more user-friendly messaging when no file data is found for a workflow.
The error we're returning in this situation is a bit vague and we should perhaps be clarified.
"No file data found" is also debatable language, but I think it tracks with the current terminology used.
> Update messaging when no workflow file/data is found

- pkg/cmd/workflow.go
Avoid deleting the workflow if creating the revision fails.
By far, the most common reasons for errors during revision processing are validation errors.
This shouldn't result in deletion of the workflow.
In the future, as we improve our validation, this could potentially provide more helpful commentary/instructions regarding fixing the workflow file and replacing the file.
Even then, deleting the workflow for any other reason would and should never be done automatically here. A destructive act of that nature could only be considered as an optional flag that has to be explicitly set.
> Do not automatically delete workflow on error

- pkg/dev/dev.go
- pkg/dev/namespace.go
Trigger functionality stopped working due to missing labels on trigger-related namespaces (i.e. `knative-serving` and `ambassador-webhook`). These labels are necessary due to network policies.
P.S. We need to define these labels in a common location, rather than hardcoding them in multiple places...
> Add necessary labels to namespaces

- pkg/cmd/metadata.go
Adds long-form help text
Formats the output of the idling server for easier copypasta
> Relay dev metadata improvements

- README.md
- docs/relay.md
- pkg/client/auth.go
- pkg/client/client.go
- pkg/client/openapi/configuration.go
- pkg/client/request.go
- pkg/client/token.go
- pkg/cmd/auth.go
- pkg/cmd/config.go
- pkg/cmd/context.go
- pkg/cmd/kubectl.go
- pkg/cmd/main.go
- pkg/cmd/token.go
- pkg/cmd/workflow.go
- pkg/config/config.go
- pkg/format/guilink.go
- pkg/util/stdin.go
* Token Management
* Create, revoke, and list tokens directly from the CLI
* Supports writing generated tokens to files
* Enhanced `auth login`
* Import token from `stdin` or file
* CLI fully supports either token or session auth 
* Full support for multiple contexts and context switching
* Includes auth storage support for easier context switching
> Add token handling

- docs/relay.md
- pkg/client/request.go
- pkg/cmd/workflow.go
- pkg/cmd/workflow_save.go
- pkg/errors/build_errors.go
- pkg/errors/errors.yaml
Prior to this commit, `relay workflow add [name] --file foo.yaml` was required to create a new workflow and `relay workflow replace [name] --file foo.yaml` was required to update an existing workflow. This meant that there was no idempotent format of the command.
This change deprecates both of these in favor of `relay workflow save [name] --file foo.yaml` that will create the workflow with the given name if it does not yet exist and will update the revision of that workflow.
There are flags to preserve the old failure modes if desired.
This change does allow `relay workflow replace [name]` (no `--file` specified) to do nothing instead of failing due to the missing flag; this behavior can be reverted if desired.
> Deprecated workflow add/replace for workflow save

- pkg/client/openapi/.openapi-generator-ignore
- pkg/client/openapi/api_connection_providers.go
- pkg/client/openapi/client.go
Handles the new Connection Providers API
(this is summarily ignored for now)
> Generate latest client from OpenAPI specification

- README.md
- docs/relay.md
- pkg/cmd/dev.go
- pkg/cmd/workflow.go
- Removes misleading/incorrect documentation and dialog output
- Adds additional context to `relay dev` command output
- Slightly improve the overall positivity of the `relay workflow save` options
- `go generate ./...` was missed, so might as well make adjustments and regenerate
> User-friendly output adjustments

- .github/workflows/ci.yaml
Adds a `go generate ./...` check to CI to ensure this is run before merging PRs.
> Add go generate check to CI

- pkg/dev/relaycore.go
Change the default `ImagePullPolicy` to `Always` for the dev environment core images.
This drastically improves the ease of testing changes to the core images.
> Change dev image pull policy to always

- docs/relay.md
- pkg/cmd/main.go
- pkg/cmd/version.go
- pkg/version/version.go
- scripts/build
Not sure if the `debug.ReadBuildInfo()` fallback is really necessary here, the example I was following used it. In our case we already have a pretty robust version calculation as part of the build script that was easy to inject so it may be fine to just fallback to the "could not determine build information" output.
> Add `version` subcommand and update build script to set necessary value

- pkg/cluster/k3d.go
Fixes an inverted error check introduced when cleaning up error handling.
Removes the check entirely for now, as we check for the existence of a cluster elsewhere.
As a general rule, it's probably a fair expectation to expect the use of the `Exists` function prior to `Create` when using this interface.
Otherwise, this logic becomes unwieldy, as it requires checking for the lack of an error code as an error, and generating a fake error to cover this scenario, which feels decidedly unclean.
May revisit this in the future.
> Resolve the existential crisis of a new cluster

- pkg/dev/dev.go
Update default Relay Installer image to `relaysh/relay-installer` instead of `relaysh/relay-install-operator`. The previous use of `relaysh/relay-install-operator` was slightly inconsistent with other naming. `Relay Installer` is arguably cleaner.
> Update default Relay Installer image

- docs/relay.md
- pkg/cmd/config.go
- pkg/config/config.go
Add commands to configure global flags. Currently, you have to either manually modify the configuration file to set global options or add the flag overrides on every command issuance. This adds an easier method (primarily for automated environments) to set global options when issuing a set of `relay` commands. Note that it still transparently requires the configuration file, due to the way the current functionality works.
This feels a bit too boilerplate, but it serves the purpose for now, without a larger rework of the underlying system.
> Add command to configure global flags

- pkg/dev/dev.go
- pkg/dev/namespace.go
Dev workflow resources are created in the `relay-tenants` namespace (consistent with our current design) instead of the target workflow namespace (legacy design). The Relay Installer is creating the `relay-tenant` namespace automatically now as well.
> Refactor tenant namespace for dev workflows
